begin
  execute immediate '
    drop database ONLINESHOPPING
  ';
exception
  when others then
    if sqlerrm like 'ORA-xxxxx%' then null;
    else raise;
    end if;
end;;
create database ONLINESHOPPING;
alter session set current_schema = "ONLINESHOPPING";


*****************************************************

create table CATEGORY (
  ID number(10) generated by default as identity(start with 1) not null,
  NAME varchar2(50) null,
  DESCRIPTION varchar2(255) null,
  IMAGE_URL varchar2(50) null,
  IS_ACTIVE number null,
  constraint PK_CATEGORY_ID
    primary key (ID)
);
create table USER_DETAIL (
  ID number(10) generated by default as identity(start with 1) not null,
  FIRST_NAME varchar2(50) null,
  LAST_NAME varchar2(50) null,
  ROLE varchar2(50) null,
  ENABLED number null,
  PASSWORD varchar2(60) null,
  EMAIL varchar2(100) null,
  CONTACT_NUMBER varchar2(15) null,
  constraint PK_USER_ID
    primary key (ID)
);
create table PRODUCT (
  ID number(10) generated by default as identity(start with 1) not null,
  CODE varchar2(20) null,
  NAME varchar2(50) null,
  BRAND varchar2(50) null,
  DESCRIPTION varchar2(255) null,
  UNIT_PRICE decimal(10, 2) null,
  QUANTITY number(10) null,
  IS_ACTIVE number null,
  CATEGORY_ID number(10) null,
  SUPPLIER_ID number(10) null,
  PURCHASES number(10) default 0 null,
  VIEWS number(10) default 0 null,
  constraint PK_PRODUCT_ID
    primary key (ID),
  constraint FK_PRODUCT_CATEGORY_ID
    foreign key (CATEGORY_ID)
    references CATEGORY (ID),
  constraint FK_PRODUCT_SUPPLIER_ID
    foreign key (SUPPLIER_ID)
    references USER_DETAIL (ID)
);
create table ADDRESS (
  ID number(10) generated by default as identity(start with 1) not null,
  USER_ID number(10) null,
  ADDRESS_LINE_ONE varchar2(100) null,
  ADDRESS_LINE_TWO varchar2(100) null,
  CITY varchar2(20) null,
  STATE varchar2(20) null,
  COUNTRY varchar2(20) null,
  POSTAL_CODE varchar2(10) null,
  IS_BILLING number null,
  IS_SHIPPING number null,
  constraint FK_ADDRESS_USER_ID
    foreign key (USER_ID)
    references USER_DETAIL (ID),
  constraint PK_ADDRESS_ID
    primary key (ID)
);
create table CART (
  ID number(10) generated by default as identity(start with 1) not null,
  USER_ID number(10) null,
  GRAND_TOTAL decimal(10, 2) null,
  CART_LINES number(10) null,
  constraint FK_CART_USER_ID
    foreign key (USER_ID)
    references USER_DETAIL (ID),
  constraint PK_CART_ID
    primary key (ID)
);
create table CART_LINE (
  ID number(10) generated by default as identity(start with 1) not null,
  CART_ID number(10) null,
  TOTAL decimal(10, 2) null,
  PRODUCT_ID number(10) null,
  PRODUCT_COUNT number(10) null,
  BUYING_PRICE decimal(10, 2) null,
  IS_AVAILABLE number null,
  constraint FK_CARTLINE_PRODUCT_ID
    foreign key (PRODUCT_ID)
    references PRODUCT (ID),
  constraint PK_CARTLINE_ID
    primary key (ID)
);
create table ORDER_DETAIL (
  ID number(10) generated by default as identity(start with 1) not null,
  USER_ID number(10) null,
  ORDER_TOTAL decimal(10, 2) null,
  ORDER_COUNT number(10) null,
  SHIPPING_ID number(10) null,
  BILLING_ID number(10) null,
  ORDER_DATE date null,
  constraint FK_ORDER_DETAIL_USER_ID
    foreign key (USER_ID)
    references USER_DETAIL (ID),
  constraint FK_ORDER_DETAIL_SHIPPING_ID
    foreign key (SHIPPING_ID)
    references ADDRESS (ID),
  constraint FK_ORDER_DETAIL_BILLING_ID
    foreign key (BILLING_ID)
    references ADDRESS (ID),
  constraint PK_ORDER_DETAIL_ID
    primary key (ID)
);
create table ORDER_ITEM (
  ID number(10) generated by default as identity(start with 1) not null,
  ORDER_ID number(10) null,
  TOTAL decimal(10, 2) null,
  PRODUCT_ID number(10) null,
  PRODUCT_COUNT number(10) null,
  BUYING_PRICE decimal(10, 2) null,
  constraint FK_ORDER_ITEM_PRODUCT_ID
    foreign key (PRODUCT_ID)
    references PRODUCT (ID),
  constraint FK_ORDER_ITEM_ORDER_ID
    foreign key (ORDER_ID)
    references ORDER_DETAIL (ID),
  constraint PK_ORDER_ITEM_ID
    primary key (ID)
);
insert into CATEGORY (
  NAME,
  DESCRIPTION,
  IMAGE_URL,
  IS_ACTIVE
)
values (
  'Laptop', 
  'This is description for Laptop category!', 
  'CAT_1.png', 
  1
);
insert into CATEGORY (
  NAME,
  DESCRIPTION,
  IMAGE_URL,
  IS_ACTIVE
)
values (
  'Television', 
  'This is description for Television category!', 
  'CAT_2.png', 
  1
);
insert into CATEGORY (
  NAME,
  DESCRIPTION,
  IMAGE_URL,
  IS_ACTIVE
)
values (
  'Mobile', 
  'This is description for Mobile category!', 
  'CAT_3.png', 
  1
);
insert into USER_DETAIL (
  FIRST_NAME,
  LAST_NAME,
  ROLE,
  ENABLED,
  PASSWORD,
  EMAIL,
  CONTACT_NUMBER
)
values (
  'Virat', 
  'Kohli', 
  'ADMIN', 
  1, 
  '$2a$06$ORtBskA2g5Wg0HDgRE5ZsOQNDHUZSdpJqJ2.PGXv0mKyEvLnKP7SW', 
  'vk@gmail.com', 
  '8888888888'
);
insert into USER_DETAIL (
  FIRST_NAME,
  LAST_NAME,
  ROLE,
  ENABLED,
  PASSWORD,
  EMAIL,
  CONTACT_NUMBER
)
values (
  'Ravindra', 
  'Jadeja', 
  'SUPPLIER', 
  1, 
  '$2a$06$bzYMivkRjSxTK2LPD8W4te6jjJa795OwJR1Of5n95myFsu3hgUnm6', 
  'rj@gmail.com', 
  '9999999999'
);
insert into USER_DETAIL (
  FIRST_NAME,
  LAST_NAME,
  ROLE,
  ENABLED,
  PASSWORD,
  EMAIL,
  CONTACT_NUMBER
)
values (
  'Ravichandra', 
  'Ashwin', 
  'SUPPLIER', 
  1, 
  '$2a$06$i1dLNlXj2uY.UBIb9kUcAOxCigGHUZRKBtpRlmNtL5xtgD6bcVNOK', 
  'ra@gmail.com', 
  '7777777777'
);
insert into USER_DETAIL (
  FIRST_NAME,
  LAST_NAME,
  ROLE,
  ENABLED,
  PASSWORD,
  EMAIL,
  CONTACT_NUMBER
)
values (
  'Khozema', 
  'Nullwala', 
  'USER', 
  1, 
  '$2a$06$4mvvyO0h7vnUiKV57IW3oudNEaKPpH1xVSdbie1k6Ni2jfjwwminq', 
  'kn@gmail.com', 
  '7777777777'
);
insert into PRODUCT (
  CODE,
  NAME,
  BRAND,
  DESCRIPTION,
  UNIT_PRICE,
  QUANTITY,
  IS_ACTIVE,
  CATEGORY_ID,
  SUPPLIER_ID,
  PURCHASES,
  VIEWS
)
values (
  'PRDABC123DEFX', 
  'iPhone 5s', 
  'apple', 
  'This is one of the best phone available in the market right now!', 
  18000, 
  5, 
  1, 
  3, 
  2, 
  0, 
  0
);
insert into PRODUCT (
  CODE,
  NAME,
  BRAND,
  DESCRIPTION,
  UNIT_PRICE,
  QUANTITY,
  IS_ACTIVE,
  CATEGORY_ID,
  SUPPLIER_ID,
  PURCHASES,
  VIEWS
)
values (
  'PRDDEF123DEFX', 
  'Samsung s7', 
  'samsung', 
  'A smart phone by samsung!', 
  32000, 
  2, 
  1, 
  3, 
  3, 
  0, 
  0
);
insert into PRODUCT (
  CODE,
  NAME,
  BRAND,
  DESCRIPTION,
  UNIT_PRICE,
  QUANTITY,
  IS_ACTIVE,
  CATEGORY_ID,
  SUPPLIER_ID,
  PURCHASES,
  VIEWS
)
values (
  'PRDPQR123WGTX', 
  'Google Pixel', 
  'google', 
  'This is one of the best android smart phone available in the market right now!', 
  57000, 
  5, 
  1, 
  3, 
  2, 
  0, 
  0
);
insert into PRODUCT (
  CODE,
  NAME,
  BRAND,
  DESCRIPTION,
  UNIT_PRICE,
  QUANTITY,
  IS_ACTIVE,
  CATEGORY_ID,
  SUPPLIER_ID,
  PURCHASES,
  VIEWS
)
values (
  'PRDMNO123PQRX', 
  ' Macbook Pro', 
  'apple', 
  'This is one of the best laptops available in the market right now!', 
  54000, 
  3, 
  1, 
  1, 
  2, 
  0, 
  0
);
insert into PRODUCT (
  CODE,
  NAME,
  BRAND,
  DESCRIPTION,
  UNIT_PRICE,
  QUANTITY,
  IS_ACTIVE,
  CATEGORY_ID,
  SUPPLIER_ID,
  PURCHASES,
  VIEWS
)
values (
  'PRDABCXYZDEFX', 
  'Dell Latitude E6510', 
  'dell', 
  'This is one of the best laptop series from dell that can be used!', 
  48000, 
  5, 
  1, 
  1, 
  3, 
  0, 
  0
);
insert into ADDRESS (
  USER_ID,
  ADDRESS_LINE_ONE,
  ADDRESS_LINE_TWO,
  CITY,
  STATE,
  COUNTRY,
  POSTAL_CODE,
  IS_BILLING,
  IS_SHIPPING
)
values (
  4, 
  '102 Sabarmati Society, Mahatma Gandhi Road', 
  'Near Salt Lake, Gandhi Nagar', 
  'Ahmedabad', 
  'Gujarat', 
  'India', 
  '111111', 
  1, 
  0
);
insert into CART (
  USER_ID,
  GRAND_TOTAL,
  CART_LINES
)
values (
  4, 
  0, 
  0
);